### PR TITLE
Feature(Issue #3) : Create a new shopping list with a uniquely generated token

### LINKED ISSUE #3: 3. As a user, I want to set up a new shopping list so I can start tracking purchased items.
A shopping list consists of a set of items associated with a user’s token. Creating a new list consists of the following sequence:

* Generate a new, unique token
* Save the token to `localStorage`
* Show the user the list view

The following script should be used to generate a suitable token: `src/lib/tokens.js`

AC:

* For users who do not already have a token/list, a button or link exists on the home screen that allows them to create a new list
* Clicking the button/link generates a new token and saves it to `localStorage`
* Once the token has been created and saved, the user is redirected to the "list" view

### PR DESCRIPTION
**Pull request by CodeMeKathy**
## Description

This Pull Request (PR) adds a new `<Home/>` component to serve as a landing page. Modifies the `<List />` component to generate a new token if one doesn't exist in local storage. Refactors the `<AddItemFirebase />` and `<AddItem />` components into one `<AddItem />` component. Changes the `<AddItem />` component to add items to the firestore database based on the user token with an added `id` parameter to each item. Lastly, refactors `<AddItem />` to modify the add item form for better accessibility.

When the user selects the list link, they are redirected to the `<List/>` component view. If no token is saved into `localStorage` the user is notified their shopping list is empty and prompted with a button to add an item. Selecting the 'add item' button generates a new, unique, user token associated with a new shopping list and the user is redirected to the `<List/>` component. 

## Related Issue

Closes Issue #3 

## Acceptance Criteria

- [X] For users who do not already have a token/list, a button or link exists on the home screen that allows them to create a new list
- [X] Clicking the button/link generates a new token and saves it to `localStorage`
- [X] Once the token has been created and saved, the user is redirected to the "list" view

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

Before - Empty List View
Before - List View
Before - Add Item View

### After

Home Page
Empty Shopping List View
Shopping List View
Present Token Shopping List View
Add Item View

## Testing Steps / QA Criteria

- From your terminal, run `git checkout kl-vh-token-setup`
- Once on the `git checkout kl-vh-token-setup` branch, in the browser, visit the new `<Home/>` page (http://localhost:3000). 
- Click the `<List/>` navigation link at the bottom of the screen to be redirected to the `<List/>` component view.
- If no token is saved within `localStorage`, the message 'Your shopping list is currently empty' with an 'add new' item button is present. If a token is already saved in `localStorage` and a shopping list does exist, the list items should be rendered. 
- To create a new shopping list, click the 'add item' button. After being redirected to the `<AddItem />` component view type in a new item and select the 'add item' button. Upon submission, a new item is added to the database associated with the user token collection.

### CODE REVIEW

**Comment by brewswain** [comment]
All AC for issue:#3  have been met-and how!.

Testing this went super smoothly, and I love the subtle UI cleanup. The project structure changes are also really nice, I love the use of `component.index`, as well as the clearer variable names given in the `Listener.service` file.

In fact this is such an excellent PR that I want to get this pulled into my repo to work from 😤

**Comment by stef-codes** [comment]
Functionality works as expected, according to the Acceptance Criteria. Great job team!

**Review by stef-codes — COMMENTED** [review]
Works as expected.

**Comment by joeylaguna** [comment]
Great job! Seeing a pattern of super clean code in this cohort with comments used in a smart, useful way, and i'm a big fan!

**Pull request merged**
